apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wzu8ngr5v-dotnet-basic
  janus-idp.io/tekton: wzu8ngr5v-dotnet-basic
  backstage.io/kubernetes-id: wzu8ngr5v-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wzu8ngr5v-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
